### ISSUE TITLE
Feature Toggle UI

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#177]
It'd be nice to have a floating box that 
- displays all the possible feature toggles, 
- displays their current state,
- allows changing that state (maybe using history api to just change the query param dynamically?)

I'm thinking we could have this floating box show automatically when the `ft` query param is present, even if its empty. 

Could also hide it behind a keyboard shortcut, or both.

If we wanted a floating box, it'd be nice to make it draggable so we can move it around to avoid it shadowing parts of the screen.

Or it could be a drop-down in the footer. 

Just throwing some ideas.

Tagging @geoffturk @kennylavender @jwicks31 for feedback and prioritization.

Labeling this as `testing` because that's where I'd use it, personally.

**Comment by geoffturk** [comment]
This sounds like a nice feature to add to `react-feature-toggles`.

I would keep this as a low priority for after the Mainnet epic is completed.

**Comment by geoffturk** [comment]
@jwicks Please add to `react-feature-toggles` repo as an improvement issue. Thanks.

**Comment by geoffturk** [comment]
Logged in: https://github.com/paralleldrive/react-feature-toggles/issues/173
