### ISSUE TITLE
Avoid `any` in reducers

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#181]
See https://github.com/poetapp/explorer-web/blob/ecc5d5e940514b80f06c2495c6f4a81a368d8d8e/src/reducers/User.ts#L14-L21 for example.

Here, both `state` and `action` are of type `any`, and `action.payload` is being spread into the state. It's completely impossible for me to know what the state will look like after running this function by just reading the code. 

There's also room for bugs — `action.payload` could be overriding anything from `state` in that spread. Is this wanted behavior?

**Comment by geoffturk** [comment]
@jwicks31 @kennylavender Please see above and provide feedback.

**Comment by kennylavender** [comment]
I think its a good idea to create an Interface for the state. I can't see any issues with that.

If our actions provide Interfaces we could also use those here instead of `any` for the action if typescript has an or operation?

```ts
const ActionTypes = ActionA | ActionB | ActionC
export const user = (state: any = defaultState, action: ActionTypes = {}) => {
  ....stuff
}
```

**Comment by kennylavender** [comment]
We do have another issue here in this reducer.

```ts
export const defaultState = {
  token: '',
  profile: {
    email: '',
    apiTokens: new Array(),
    verified: false,
    createdAt: '',
  },
}
```
This case adds a user property to the state that does not exist in the initial state, not sure if that is done on purpose or not, if it was on purpose it should'nt be.
````
case Actions.SetTokenLogin.SET_TOKEN_LOGIN:
      return {
        ...state,
        user: {
          ...state.user,
          token: action.payload.token,
        },
      }
```

**Comment by kennylavender** [comment]
I think spreading payload is fine **if** our action creators are designed and coupled to a specific reducer and filter out unnecessary properties from objects that a caller of the action creator might add.

But, based on the folder structure, we are splitting our files by type instead of by feature, so our actions are more global than being tied to a specific reducer, so spreading payload is probably not a good idea, not sure if its unsafe, but it will likely result in extra state being stored in the reducer when it shouldn't be.

**Comment by warrenv** [comment]
Just a note to clarify that each reducer only receives it's slice of the state, not the entire state. So spreading an action payload would not "override anything in state".

**Comment by warrenv** [comment]
Usually, in the case of tokens, the non-existence of the token property in the user slice is used to indicate the user is *not* logged in. We would have to set token to `null` in the initial state if we always wanted to see it there.

**Comment by kennylavender** [comment]
> Usually, in the case of tokens, the non-existence of the token property in the user slice is used to indicate the user is not logged in. We would have to set token to null in the initial state if we always wanted to see it there.

I think null would be an improvement, just so someone looking at the reducer knows there is a possibility of values there in the future. What do you guys think?

**Comment by lautarodragan** [comment]
> I think its a good idea to create an Interface for the state. I can't see any issues with that.

Totally! [I thought we already did, though](https://github.com/poetapp/explorer-web/blob/master/src/store/PoetAppState.ts). 

> If our actions provide Interfaces we could also use those here instead of any for the action if typescript has an or operation?

It does, and maybe [discriminated union types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions) can help in this case.

```ts
interface Square {
    kind: "square";
    size: number;
}
interface Rectangle {
    kind: "rectangle";
    width: number;
    height: number;
}
interface Circle {
    kind: "circle";
    radius: number;
}

type Shape = Square | Rectangle | Circle;

function area(s: Shape) {
    switch (s.kind) {
        case "square": return s.size * s.size;
        case "rectangle": return s.height * s.width;
        case "circle": return Math.PI * s.radius ** 2;
    }
}
```

> I think spreading payload is fine if our action creators are designed and coupled to a specific reducer and filter out unnecessary properties from objects that a caller of the action creator might add.

> But, based on the folder structure, we are splitting our files by type instead of by feature, so our actions are more global than being tied to a specific reducer, so spreading payload is probably not a good idea, not sure if its unsafe, but it will likely result in extra state being stored in the reducer when it shouldn't be.

Agreed. To be on the safe side, I'd much rather avoid spreading the action payload as a general rule.

> Usually, in the case of tokens, the non-existence of the token property in the user slice is used to indicate the user is not logged in. We would have to set token to null in the initial state if we always wanted to see it there.

> I think null would be an improvement, just so someone looking at the reducer knows there is a possibility of values there in the future. What do you guys think?

I personally prefer using falsey values (undefined, false, null, etc) instead of strict non-existence. (non-existence evaluates to `undefined`). So `const userIsLoggedIn = state.user && state.user.token`.

**Comment by warrenv** [comment]
I don't believe you can set a property in redux state to undefined - redux ignores the property in that case.

**Comment by geoffturk** [comment]
Flagging in PNE epic as a reminder.
