### ISSUE TITLE
OnChange Events: React.SyntheticEvent replace any

### ISSUE THREAD

**Issue by jwicks31** [poetapp/explorer-web#195]
Comment from @lautarodragan :
OK, I went and checked an old project of mine and then remembered the correct way to do this.

`SyntheticEvent` takes a generic parameter than can be used to type `currentTarget`. 

I think it would look like this:

```ts
readonly onChangeRepeatPassword = (e: React.SyntheticEvent<HTMLInputElement>, data: any, elements: any): void => {
    const target = e.currentTarget;
    const value = target.value;
```

There's also many more-specific interfaces that extend from SyntheticEvent, such as `KeyboardEvent` and `MouseEvent`.

Here's the [source code of the React typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L567).

Here's a [`target` vs `currentTarget`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12239) related discussion. 

And here's [documentation on `currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget).

For our current use case I don't think we really need to change anything in this PR, but I wanted to leave this here as some sort of documentation on the topic.

I believe in onChange events using target and currentTarget has the same effect, and using the generic parameter of SyntheticEvent or casting doesn't make any real different either (since neither do any actual type checking).

**Comment by geoffturk** [comment]
No need to tackle in explorer-web. Flagging it for the PNE epic instead as a reminder.
