### ISSUE TITLE
Work id not available

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#214]
This work id is indexed in Google, but is not available in explorer (not a question of sync).

This can create the idea that some data just got deleted from the immutable ledger or something else. What happened in this case?

https://explorer.po.et/works/d347a6c7372a99539a8306fc5f02ad39afeb88b64f82d0dd3b7303f194b53912

**Comment by lautarodragan** [comment]
Thanks for the bug report @ar-anvd!

I cannot find that work in Frost API either. Without further information, I can't really tell what happened, or whether it ever existed at all or that URL just got indexed by google for some random reason.

Can you provide more information on that work?

**Comment by ar-anvd** [comment]
@lautarodragan 

Unfortunately I don't have info to help debugging. But google is indexing a ton of unavailable works. This is not good.

https://explorer.po.et/works/df232c50ccfb1cf6bdc7bd5825c6f0506f9b14ad563f0c5833e22e2aecb5ee85
https://explorer.po.et/works/85b69dad9198c2b25458f7d5eb53e3fb373fe7250d349c9520811c8a46baa25e
https://explorer.po.et/works/d347a6c7372a99539a8306fc5f02ad39afeb88b64f82d0dd3b7303f194b53912
https://explorer.po.et/works/9f4a4a5bd5cd33575d54459a8eb969effe883dd2412f7bfa7929d8f8e96a1fc2
https://explorer.po.et/works/599095c74277489addb23942197575c0907704a99620b959110f373596b0207b
https://explorer.po.et/works/3b1efcd6471fae7cbc8dd890d2da99555adbedb85a13920f1c414ce2c58096a9
https://explorer.po.et/works/9468caf19112de80fcd09213773bc6879e5ef8cc7d8e7bddd606a4eaa2dfe17b
https://explorer.po.et/works/9e44b9d97e80ce70467308d4b15c503d52e04f065a5a059115af4d7286c6d7e1

**Comment by geoffturk** [comment]
The above work URLs no longer appear to be indexed in Google.
