### ISSUE TITLE
Remove redirects and proxy

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#315]
Now that Frost API supports CORS for all endpoints we should be able to get rid of the netlify redirects and the local dev proxy, which just add unnecessary complexity.

We'll need to replace them with a simple environment variable `FROST_API_URL` .

## Important

Since the new Frost API isn't deployed in production, implementing this change in Frost Web would break things. Will need to sync deployment.

**Comment by lautarodragan** [comment]
@geoffturk I'd implement this for mainnet-beta but it isn't critical - we can leave it in mainnet-launch and move it to mainnet-beta as we approach to completeness. 

Should be a small change.

**Comment by geoffturk** [comment]
Moving to Mainnet-beta since it is needed for the "fresh start" approach.
