### ISSUE TITLE
Install @po.et/poet-js: Netlify Breaking

### ISSUE THREAD

**Issue by jwicks31** [poetapp/explorer-web#418]
Netlify will not build whenever the package @po.et/poet-js is installed. We are able to get around the Travis build failing with the following additions to .travis.yml:
```
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-5 /usr/bin/g++
```

And to Dockerfile:
```
RUN echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list
 RUN apt-get update && apt-get install -y rsync \
  gcc-5 \
  g++-5 \
  && rm -rf /var/lib/apt/lists/* \
  && rm /etc/apt/sources.list.d/unstable.list
```

But Netlify was still failing. We have removed the package for now. Potential Solution: https://github.com/netlify/build-image/issues/183

Opened an Issue with Netlify here:
https://github.com/netlify/build-image/issues/214

Closely related to https://github.com/poetapp/poet-js/issues/250

**Comment by geoffturk** [comment]
@warrenv @wzalazar FYI, and to see if you have any ideas here...

**Comment by lautarodragan** [comment]
Asked support about this, got this reply:

> Hi Lautaro,You don't have root permissions in our build container, so you can't run any of those commands.  You don't have a lot of good options to install things like gcc/g++ - but those are already in the build environment.  Do you need some specific version of them for your build?  rsync is already in there too :)

```
buildbot@62e80c2d067d:/$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

.buildbot@62e80c2d067d:/$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

buildbot@62e80c2d067d:/$ rsync --versionrsync  version 3.1.0  protocol version 31
```
 
I guess all we can do is wait. Not super happy about this.

**Comment by wzalazar** [comment]
well, the good news is that they respond. So, the question here, How we can push the update of the dependency?

**Comment by lautarodragan** [comment]
> well, the good news is that they respond. 

True. They were actually really fast to respond and gave me a pretty thorough response.

> So, the question here, How we can push the update of the dependency?

They said we can't. Then they asked me if we really needed specific versions, I replied yes and am waiting for more input.

**Comment by wzalazar** [comment]
yes, maybe support can't do anything. My real question is if this [repository](https://github.com/netlify/build-image/issues/214) is that uses Netlify for the builds

in the Readme says:

```
This repository contains the tools to make the build image Netlify uses to build a site from git (for continuous deployment.)

You can also use the image this generates to test locally if you're having build issues.
```

**Comment by lautarodragan** [comment]
That's correct, Netlify uses that Docker image to build sites. We can actually download it and test locally to reproduce bugs, which is something I'd like to do to be 100% sure we know the issue.

@krobi64 are we 100% sure the issue is with the version of gcc / g++, or should we test adding the commands [you commented on the PR](https://github.com/poetapp/explorer-web/pull/389#issuecomment-438388788) to the Netlify Docker image and confirm that it passes with them and fails without them?

**Comment by lautarodragan** [comment]
According to @krobi64 and @wzalazar, we could try [setting `--no-optional`](https://github.com/poetapp/poet-js/issues/250#issuecomment-442963885) and see if we get Netlify to build correctly with Po.et JS

@geoffturk this is something I'd like us to try in explorer-web (the current version, not the new hybrid one) to rule out this potential issue with Po.et JS.

**Comment by geoffturk** [comment]
OK. Reassigning to @wzalazar so he can try it out.

**Comment by wzalazar** [comment]
I tried with the option `--no-optional` with `npm` and `yarn` also, but the build always fails.

- `npm install --no-optional`
- `yarn install --ignore-optional`

Also, I tried with other options that the community suggest like as, for example:

- --no-optional
- --no-package-lock
- --production
- --no-shrinkwrap

This test was done with Netlify image, https://github.com/netlify/build-image. Also, I checked if there are possibilities to install the dependencies before to install the `node_modules`, but it's not possible to install libraries before the commands `npm install` or `yarn install`.

I checked the scripts [run-build.sh](https://github.com/netlify/build-image/blob/master/run-build.sh) and [run-build-functions.sh](https://github.com/netlify/build-image/blob/master/run-build-functions.sh) for if there is a possibility to exist a condition to avoid the `npm install` but there is not.

@lautarodragan What do you say?

**Comment by lautarodragan** [comment]
great work @wzalazar. 

@geoffturk let's park this for now.

**Comment by geoffturk** [comment]
OK. Parked it in the backlog.

Maybe we can avoid this issue when we trial out Now.sh for the next gen app. @jwicks31 Keep this in mind while looking into it.
