### ISSUE TITLE
explorer.poetnetwork.net: legacy styles on the confirm account page

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/explorer-web#433]
When I click on the link to confirm my account from my email, I'm taken to a site that has the old styles (all blue rather than green).

This site automatically redirects to the dashboard after a second or so, so it's no biggie.

@geoffturk @jwicks31

**Comment by geoffturk** [comment]
![2018-11-22 15 17 44](https://user-images.githubusercontent.com/32190662/48908229-fb4e7580-ee69-11e8-85ca-e5abf32c168b.gif)

**Comment by jwicks31** [comment]
Closing this and moving over to frost-web.
