### ISSUE TITLE
No tokens available

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#634]
![a](https://user-images.githubusercontent.com/4244340/55155459-50b7cd80-514f-11e9-9eea-787008bd9cdc.png)

When opening a private tab then it works normally and show the tokens. Probably some issue with cache.

**Comment by lautarodragan** [comment]
"Expired Token" means that the session has finished. Can you try logging out and back in?

**Comment by ar-anvd** [comment]
@lautarodragan you are correct. It works. Anyway, I would suggest an automatic logout in that case. 

A random user will never understand what "Expired Token" means.

**Comment by lautarodragan** [comment]
Thanks. Created https://github.com/poetapp/explorer-web/issues/642 to track this.
