### ISSUE TITLE
404 error using API 

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#636]
I think there is a new issue in https://api.poetnetwork.net/ . I am receiving 404, and the same code works until two or three days ago.

```
r = requests.post(self.url, headers=self.headers, data=json.dumps(work))

if r.status_code == 200:
    ...
else:
   raise ValueError('Error in frost api ' + str(r.status_code) + '-' + r.text)
```

ValueError: Error in frost api 404-Not Found

**Comment by lautarodragan** [comment]
@ar-anvd we have not deployed a new version of the API in the past week and a half or so.

Requesting the root route always resulted in 404 though. Are you requesting that route?

**Comment by ar-anvd** [comment]
@lautarodragan March 25th, 2019 is the last day that I was able to creat a work. I will try to debug this today on my side . But I am sure that I did not make any change. The code is exactly the same.

Thank you

**Comment by lautarodragan** [comment]
@ar-anvd have you still been unable to create new works since March 25th?

**Comment by ar-anvd** [comment]
@lautarodragan please test with this gist. 

https://gist.github.com/ar-anvd/41f4841aafce22942d5c815db75eb350

Replace token. I can't make this work using the same API token that worked fine in the past. Now the error is 409. **This example is not using a new account, or a new API token.**
