### ISSUE TITLE
Internal error when recover password

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#641]
https://explorer.poetnetwork.net/forgot-password

Just try with asd@the-first.email. Apparently this only occurs sometimes.

![Untitled-1](https://user-images.githubusercontent.com/4244340/55282861-db155280-5344-11e9-8edf-0f2513454d67.png)

**Comment by lautarodragan** [comment]
Should be working now. Can you confirm @ar-anvd?

**Comment by ar-anvd** [comment]
@lautarodragan It seems working correctly.  Maybe you can improve the message

_Great! An email has been sent to kiet.royer@bullstore.net with a link to reset the password. Please check your inbox._ In fact the email was not send (The specified resource does not exist).
