### ISSUE TITLE
Remove Work Not Found Toast

### ISSUE THREAD

**Issue by elliotfeeny** [poetapp/explorer-web#658]

**Comment by elliotfeeny** [comment]
didn't show up when I just submitted one, but it did this morning. not sure what the issue is

**Comment by elliotfeeny** [comment]
looks like it comes up when you click on the link before it has been confirmed. can we add a "waiting for claim to confirm" message instead of having it blank?

**Comment by lautarodragan** [comment]
We could go with either. Both require redesigning the system that handles non-success server responses. Once that's in place, either option should require the same amount of time/effort to implement.
