### ISSUE TITLE
Error with expired certificate 

### ISSUE THREAD

**Issue by ar-anvd** [poetapp/explorer-web#666]
![Screenshot from 2019-05-28 16-53-48](https://user-images.githubusercontent.com/4244340/58493036-04e2ce00-816a-11e9-8ff5-f2b4a3b955cb.png)

**Comment by lautarodragan** [comment]
@WesleyCharlesBlake

**Comment by lautarodragan** [comment]
@ar-anvd we haven't been able to reproduce on our side - certificate shows fine for us.

Are you still having this issue?

**Comment by ar-anvd** [comment]
@lautarodragan It's fine
